<?php

/**
 * @file
 * Domain-based access control for menu link.
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_ENTITY_TYPE_presave().
 *
 * Fires only if Devel Generate module is present, to assign test menu
 * link content to domains.
 */
function domain_menu_access_menu_link_content_presave(EntityInterface $node) {
  domain_access_presave_generate($node);
}

/**
 * Implements hook_form_BASE_FORM_ID_alter() for \Drupal\menu_link_content\MenuLinkContentForm.
 *
 * Move Domain Access fields to an advanced tab like other node settings.
 */
function domain_menu_access_form_menu_link_content_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  /** @var \Drupal\menu_link_content\Form\MenuLinkContentForm $form_object */
  $form_object = $form_state->getFormObject();
  /** @var \Drupal\menu_link_content\Entity\MenuLinkContent $entity */
  $entity = $form_object->getEntity();

  $config = \Drupal::config('domain_access.settings')->get('menu_enabled');

  if (!empty($config[$entity->getMenuName()])) {
    $form['domain'] = array(
      '#type' => 'details',
      '#title' => t('Domain'),
      '#open' => TRUE,
      '#weight' => 25,
    );

    $form[DOMAIN_ACCESS_FIELD]['#group'] = 'domain';
    $form[DOMAIN_ACCESS_ALL_FIELD]['#group'] = 'domain';

    // Add the options hidden from the user silently to the form.
    $manager = \Drupal::service('domain.element_manager');
    $form = $manager->setFormOptions($form, $form_state, DOMAIN_ACCESS_FIELD);
  }
  else {
    $form[DOMAIN_ACCESS_FIELD]['#access'] = FALSE;
    $form[DOMAIN_ACCESS_ALL_FIELD]['#access'] = FALSE;
  }
}

/**
 * Implements hook_form_alter().
 */
function domain_menu_access_form_domain_access_settings_alter(&$form, FormStateInterface $form_state, $form_id) {
  $config = \Drupal::config('domain_access.settings');

  /** @var \Drupal\Core\Entity\EntityStorageInterface $menu_storage */
  $menu_storage = \Drupal::service('entity.manager')->getStorage('menu');

  $options = [];
  /** @var \Drupal\system\Entity\Menu $menu */
  foreach ($menu_storage->loadMultiple() as $menu) {
    $options[$menu->getOriginalId()] = $menu->get('label');
  }
  asort($options, SORT_NATURAL);

  $form['menu_enabled'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Enable Domain Access fields on menu link contents:'),
    '#options' => $options,
    '#default_value' => $config->get('menu_enabled') ? : [],
    '#description' => t('Domain Access fields will be provided on each link to allow domain restrictions. Domain Menu Blocks will be provided for enabled menus.'),
  );

  $form['actions']['submit']['#submit'][] = 'domain_menu_access_form_submit';
}

function domain_menu_access_form_submit(array &$form, FormStateInterface $form_state) {
  $config_factory = \Drupal::configFactory();
  $config_factory->getEditable('domain_access.settings')
    ->set('menu_enabled', $form_state->getValue('menu_enabled'))
    ->save();

  /** @var \Drupal\Core\Block\BlockManager $blockManager */
  $blockManager = \Drupal::service('plugin.manager.block');
  $blockManager->clearCachedDefinitions();
}
